# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest01LMS():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test01LMS(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-900:nth-child(1) > .bg-gray-800:nth-child(1) > .font-semibold").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-700:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-700:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-700:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3A block").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-900:nth-child(2) > .bg-gray-800:nth-child(1) > .font-semibold").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-700").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3A block").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-900:nth-child(1) > .bg-gray-800:nth-child(2) > p:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-700:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-700:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-700:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3A block").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-800").click()
    self.driver.find_element(By.CSS_SELECTOR, ".relative:nth-child(2) .block:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border").click()
    self.driver.find_element(By.CSS_SELECTOR, ".border").send_keys("Harry Potter")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-700:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-gray-700").click()
    self.driver.find_element(By.ID, "price").click()
    self.driver.find_element(By.ID, "price").send_keys("600")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-blue-700:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3A block").click()
    self.driver.close()
  
